[[pages]]
path = "pages/scrapegraphai_bedrock.py"
name = "Home"
icon = "ğŸ¡"

[[pages]]
path = "pages/smart_scraper.py"
name = "Smart Scraper"
icon = "ğŸ¥"

[[pages]]
path = "pages/csv_scraper.py"
name = "CSV Scraper"
icon = "ğŸ´"

[[pages]]
path = "pages/json_scraper.py"
name = "JSON Scraper"
icon = "ğŸŒ¸"

[[pages]]
path = "pages/xml_scraper.py"
name = "XML Scraper"
icon = "ğŸ§¾"

[[pages]]
path = "pages/script_generator.py"
name = "Script Generator"
icon = "ğŸ‘¨â€ğŸ’»"

[[pages]]
path = "pages/search_graph.py"
name = "Search Graph"
icon = "ğŸ”"
